blog_app/crud-backend/src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"post_list"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"post_list"})
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=175, unique=true)
     * @Groups({"post_list"})
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime")
     */
    private DateTime $publishedAt;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Groups({"post_list"})
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $seo_title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $seo_desc;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $google_json;

    /**
     * @ORM\ManyToOne(targetEntity=PostType::class, inversedBy="post")
     * @ORM\JoinColumn(nullable=false)
     * @Groups({"post_list"})
     */
    private $postType;

    /**
     * @ORM\OneToMany(targetEntity=PostImage::class, mappedBy="post", cascade={"remove"})
     */
    private $postImages;

    /**
     * @Groups({"post_list"})
     */
    private $previewPath;

    /**
     * @Groups({"post_list"})
     */
    private $fullSizePath;


    public function __construct()
    {
        $this->postImages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @Groups({"post_list"})
     */
    public function getPublishedAt()
    {
        return $this->publishedAt->format('c');
    }

    public function setPublishedAt(DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @Groups({"post_list"})
     */
    public function getSeoTitle(): ?string
    {
        return $this->seo_title;
    }

    public function setSeoTitle(?string $seo_title): self
    {
        $this->seo_title = $seo_title;

        return $this;
    }

    /**
     * @Groups({"post_list"})
     */
    public function getSeoDesc(): ?string
    {
        return $this->seo_desc;
    }

    public function setSeoDesc(?string $seo_desc): self
    {
        $this->seo_desc = $seo_desc;

        return $this;
    }

    /**
     * @Groups({"post_list"})
     */
    public function getGoogleJson(): ?string
    {
        return $this->google_json;
    }

    public function setGoogleJson(?string $google_json): self
    {
        $this->google_json = $google_json;

        return $this;
    }

    public function setNowAsPublishedAt(): self
    {
        $this->publishedAt = new DateTime;

        return $this;
    }

    /*PostType get & set*/
    /**
     * @Groups({"post_list"})
     */
    public function getPostType()
    {
        return $this->postType->getPostTypeName();
    }

    public function setPostType(?PostType $postType): self
    {
        $this->postType = $postType;
        return $this;
    }

    /**
     * @return Collection|PostImage[]
     */
    public function getPostImages()
    {
        return $this->postImages;
    }

    public function addPostImage(PostImage $postImage): self
    {
        if (!$this->postImages->contains($postImage)) {
            $this->postImages[] = $postImage;
            $postImage->setPost($this);
        }

        return $this;
    }

    public function removePostImage(PostImage $postImage): self
    {
        if ($this->postImages->removeElement($postImage)) {
            // set the owning side to null (unless already changed)
            if ($postImage->getPost() === $this) {
                $postImage->setPost(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     * @Groups({"post_list"})
     */
    public function getPreviewPathFront()
    {
        $arr = $this->postImages->toArray();
        foreach ($arr as $value) {
            $this->previewPath = $value->getPreviewImagePath();
        }
        return $this->previewPath;
    }

    /**
     * @return mixed
     * @Groups({"post_list"})
     */
    public function getFullSizePathFront()
    {
        $arr = $this->postImages->toArray();
        foreach ($arr as $value) {
            $this->fullSizePath = $value->getFullsizeImagePath();
        }
        return $this->fullSizePath;
    }



}

blog_app/crud-backend/templates/client-side/blog.html.twig
{% extends 'base.html.twig' %}

{% block seo %}
    <title>ITPflege blog</title>
    <meta name="description"
          content="We share our experience in developing and maintenance sites with our clients. Read ITPflege posts to improve your website effectiveness">
{% endblock %}

{% block opengraph %}
    <meta property="og:title" content="ITPflege blog">
    <meta property="og:site_name" content="ITPflege.com">
    <meta property="og:url" content="{{ app.request.getBaseURL() }}">
    <meta property="og:description"
          content="We share our experience in developing and maintenance sites with our clients. Read ITPflege posts to improve your website effectiveness">
    <meta property="og:type" content="website">
    <meta property="og:image" content="https://itpflege.com/test.png">
    <meta property="og:locale" content="us_US"/>
    <meta property="article:published_time" content="2021-09-15T17:27:58+00:00"/>
    <meta property="article:modified_time" content="2021-09-15T21:21:40+00:00"/>
    <meta name="twitter:card" content="summary_large_image"/>
    <meta name="twitter:creator" content="@ITPfege"/>
    <meta name="twitter:site" content="@ITPflege"/>
    <meta name="twitter:label1" content="ITpflege Command"/>
    <meta name="twitter:data1" content="admin"/>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/particles.js') }}" defer="defer"></script>
    <script src="{{ asset('js/particles-secondary.js') }}" defer="defer"></script>
{% endblock %}

{% block templateContentArea %}

    <div class="particles">
        <h1 class="servicecollection__header">Blog</h1>
        <div id="particles-js-services" class="blog__particles_background"></div>
    </div>

    <div class="blog">
        <h1 class="blog__header">He-he, it's our blog! Our vision to technologies</h1>
        <div class="frontpage__blog_post">
            <div class="uk-child-width-1-3@m uk-child-width-1-2@s" uk-grid>
                {% for post in posts %}
                    <div>
                        <div class="uk-card uk-card-default">
                            <div class="uk-card-media-top">
                                {# <img src="{{ asset('img/image-2.jpg') }}" alt=""> #}
                                <img class="post__preview_image" src="{{ post.postImages.first}}">
                            </div>
                            <div class="uk-card-body">
                                <h3 class="uk-card-title"><a class="blog__card_link"
                                                             href="/blog/{{ post.slug }}">{{ post.title }}</a></h3>
                                <p>{{ post.seoDesc }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

blog_app/crud-backend/templates/client-side/contacts.html.twig
{% extends 'base.html.twig' %}

{% block seo %}
    <title>{{ contacts.seoTitle }}</title>
    <meta name="description" content="{{ contacts.seoDesc }}">
{% endblock %}

{% block opengraph %}
    <meta property="og:title" content="ITPflege. {{ contacts.seoTitle }}">
    <meta property="og:site_name" content="ITPflege.com">
    <meta property="og:url" content="{{ app.request.getBaseURL() }}">
    <meta property="og:description" content="{{ contacts.seoDesc }}">
    <meta property="og:type" content="website">
    <meta property="og:image" content="https://itpflege.com/test.png">
    <meta property="og:locale" content="us_US"/>
    <meta property="article:published_time" content="2021-09-15T17:27:58+00:00"/>
    <meta property="article:modified_time" content="2021-09-15T21:21:40+00:00"/>
    <meta name="twitter:card" content="summary_large_image"/>
    <meta name="twitter:creator" content="@ITPfege"/>
    <meta name="twitter:site" content="@ITPflege"/>
    <meta name="twitter:label1" content="ITpflege Command"/>
    <meta name="twitter:data1" content="admin"/>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/particles.js') }}" defer="defer"></script>
    <script src="{{ asset('js/particles-secondary.js') }}" defer="defer"></script>
    <script type="application/ld+json">
		{{ contacts.googleJson|raw }}
    </script>
{% endblock %}

{% block templateContentArea %}

    <div class="particles">
        <h1 class="servicecollection__header">Contacts</h1>
        <div id="particles-js-services" class="blog__particles_background"></div>
    </div>

    <div class="contactpage">
        <div class="contactpage__info">
            <div class="contactpage__section_right">
                <h2 class="contactpage__right_header">Where we operate</h2>
                <hr class="uk-divider-small">
                <p class="contactpage__right_text">We are located in St. Petersburg, Russia. We work with local clients
                    and SOHO companies from the Baltic countries.</p>
                <h2 class="contactpage__right_header">First meeting</h2>
                <hr class="uk-divider-small">
                <p class="contactpage__right_text">ITpflege is not business junkies and we value informal communication.
                    You can visit our greatest city, the e-visa required. So, we are not Scatman fans and we really love
                    to use e-mail and messengers to communicate.</p>
            </div>
            <div class="uk-divider-vertical contactpage__divider_vertical"></div>
            <div class="contactpage__section_left">
                <h2 class="contactpage__header_sub">Contact</h2>
                <hr class="uk-divider-small">
                <div class="contactpage__text">
                    <p>Customer service: 11.00 to 21.00 (GMT +3)</p>
                    <p>E-mail:
                        <a class="contactpage__connect" href="mailto:test@itpflege.com">info@itpflege.com</a>
                    </p>
                    <p>Messengers:
                        <a class="contactpage__connect" href="https://api.whatsapp.com/send/?phone=79218636930&text=Message+from+ITPflege+site&app_absent=0">WhatsApp</a>
                        |
                        <a class="contactpage__connect" href="#">Fb Messenger</a>
                        |
                        <a class="contactpage__connect" href="tg://resolve?domain=sodegov">Telegram</a>
                    </p>
                </div>
{# Contact Form #}
{#                <div class="contactpage__form">#}
{#                    <h2 class="contactpage__header_sub">Contact Form</h2>#}
{#                    <hr class="uk-divider-small">#}
{#                    {{ render(controller('App\\Controller\\ContactController::index')) }}#}
{#                </div>#}
            </div>
        </div>
    </div>
    <div class="google__maps" style="width: 100%">
        <iframe width="100%" height="440" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"
                src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=%D0%B6%D0%B4%D0%B0%D0%BD%D0%BE%D0%B2%D1%81%D0%BA%D0%B0%D1%8F%20%D0%BD%D0%B0%D0%B1%D0%B5%D1%80%D0%B5%D0%B6%D0%BD%D0%B0%D1%8F%20%D0%B4%D0%BE%D0%BC%203+(ITpflege)&amp;t=&amp;z=13&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"></iframe>
    </div>
{% endblock %}

blog_app/crud-backend/templates/client-side/customer-services.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
	{{ parent() }}
	<script src="{{ asset('js/particles.js') }}" defer="defer"></script>
	<script src="{{ asset('js/particles-primary.js') }}" defer="defer"></script>
	<script type="application/ld+json">
		{{ customerServices.googleJson|raw }}
	</script>
{% endblock %}

{% block seo %}
	<title>{{ customerServices.seoTitle }}</title>
	<meta name="description" content="{{ customerServices.seoDesc }}">
{% endblock %}

{% block opengraph %}
	<meta property="og:title" content="{{ customerServices.seoTitle }}">
	<meta property="og:site_name" content="ITPflege.com">
	<meta property="og:url" content="https://itpflege.com">
	<meta property="og:description" content="{{ customerServices.seoDesc }}">
	<meta property="og:type" content="website">
	<meta property="og:image" content="https://itpflege.com/test.png">
	<meta property="og:locale" content="us_US"/>
	<meta property="article:published_time" content="2019-11-05T17:27:58+00:00"/>
	<meta property="article:modified_time" content="2020-01-09T21:21:40+00:00"/>
	<meta name="twitter:card" content="summary_large_image"/>
	<meta name="twitter:creator" content="@ITPfege"/>
	<meta name="twitter:site" content="@ITPflege"/>
	<meta name="twitter:label1" content="ITpflege Command"/>
	<meta name="twitter:data1" content="admin"/>
{% endblock %}

{% block stylesheets %}
	{{ parent() }}
{% endblock %}

{% block templateContentArea %}

{{ customerServices.content | raw }}

<div class="seo__block">
	<h2 class="seo__block_header">ITpflege.com - b2c sites and online stores development</h2>
	<p class="seo__block_description">We have been developing websites since 2009. ITPflege provides services for creating web solutions for SOHO business, both simple landing pages, online stores or web applications. Applying modern approaches to web development, we together with you control the quality of the work performed throughout the entire process of creating a website. We are dedicated to the result and your success with long-term cooperation.</p>
</div>
{% endblock %}

blog_app/crud-backend/templates/client-side/front-page.html.twig
{% extends 'base.html.twig' %}

{% block seo %}
    <title>{{ frontpage.seoTitle }}</title>
    <meta name="description" content="{{ frontpage.seoDesc }}">
{% endblock %}

{% block opengraph %}
    <meta property="og:title" content="ITPflege. {{ frontpage.seoTitle }}">
    <meta property="og:site_name" content="ITPflege.com">
    <meta property="og:url" content="{{ app.request.getBaseURL() }}">
    <meta property="og:description" content="{{ frontpage.seoDesc }}">
    <meta property="og:type" content="website">
    <meta property="og:image" content="https://itpflege.com/test.png">
    <meta property="og:locale" content="us_US"/>
    <meta property="article:published_time" content="2021-09-15T17:27:58+00:00"/>
    <meta property="article:modified_time" content="2021-09-15T21:21:40+00:00"/>
    <meta name="twitter:card" content="summary_large_image"/>
    <meta name="twitter:creator" content="@ITPfege"/>
    <meta name="twitter:site" content="@ITPflege"/>
    <meta name="twitter:label1" content="ITpflege Command"/>
    <meta name="twitter:data1" content="admin"/>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/mainPageScreen.js') }}" async></script>
    <script type="application/ld+json">
		{{ frontpage.googleJson|raw }}
    </script>
{% endblock %}

{% block templateContentArea %}

    <div class="frontpage__banner">
        <div class="frontpage__animation_text">
            <h2>
                ITPflege – web development in Latvia, Estonia and Finland<br><br>
                Websites and online stores development, e-commerce and CRMs support since 2009
            </h2>
            <button onclick="location.href='{{ path('services-list') }}'" class="uk-button frontpage__button">All
                services
            </button>
        </div>
        <canvas id='world' class="frontpage__animation"></canvas>
    </div>

    {{ frontpage.content|raw }}

    <div class="frontpage__blog">
        <h2 class="frontpage__services_header">He-he, it's our blog! Our vision to technologies</h2>
        <div class="uk-child-width-1-3@m uk-child-width-1-3@s" uk-grid>
            {% for post in frontpagePosts %}
                <div>
                    <div class="uk-card uk-card-default">
                        <div class="uk-card-media-top">
                            <img class="post__preview_image" src="{{ post.postImages.first}}" alt="{{ post.seoDesc }}">
                        </div>
                        <div class="uk-card-body">
                            <h3 class="uk-card-title">
                                <a class="blog__card_link" href="/blog/{{ post.slug }}">{{ post.title }}</a>
                            </h3>
                            <p>{{ post.seoDesc }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

blog_app/crud-backend/templates/client-side/post.html.twig
{% extends 'base.html.twig' %}

{% block seo %}
	<title>{{ post.SeoTitle }}</title>
	<meta name="description" content="{{ post.SeoDesc }}">
{% endblock %}

{% block javascripts %}
	{{parent()}}
	<script type="application/ld+json">
		{{ post.googleJson|raw }}
	</script>
{% endblock %}

{% block opengraph %}
	{{ include('client-side/__opengraphSnippet.html.twig') }}
{% endblock %}

{% block templateContentArea %}
	<div class="blog__posthead">
		<h1 class="blog__posthead_color">{{ post.title }}</h1>
	</div>

	<div class="frontpage__blog">
		<div class="blog__post_content">
			{{ post.content|raw }}
		</div>
	</div>
	{{ include('client-side/__contactFooter.html.twig') }}
{% endblock %}

blog_app/crud-backend/templates/client-side/services-list.html.twig
{% extends 'base.html.twig' %}

{% block seo %}
    <title>{{ serviceslist.seoTitle }}</title>
    <meta name="description" content="{{ serviceslist.seoDesc }}">
{% endblock %}

{% block opengraph %}
    <meta property="og:title" content="ITPflege. {{ serviceslist.seoTitle }}">
    <meta property="og:site_name" content="ITPflege.com">
    <meta property="og:url" content="{{ app.request.getBaseURL() }}">
    <meta property="og:description" content="{{ serviceslist.seoDesc }}">
    <meta property="og:type" content="website">
    <meta property="og:image" content="https://itpflege.com/test.png">
    <meta property="og:locale" content="us_US"/>
    <meta property="article:published_time" content="2021-09-15T17:27:58+00:00"/>
    <meta property="article:modified_time" content="2021-09-15T21:21:40+00:00"/>
    <meta name="twitter:card" content="summary_large_image"/>
    <meta name="twitter:creator" content="@ITPfege"/>
    <meta name="twitter:site" content="@ITPflege"/>
    <meta name="twitter:label1" content="ITpflege Command"/>
    <meta name="twitter:data1" content="admin"/>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/particles.js') }}" defer="defer"></script>
    <script src="{{ asset('js/particles-secondary.js') }}" defer="defer"></script>
    <script type="application/ld+json">
		{{ serviceslist.googleJson|raw }}
    </script>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/roadmap.css') }}">
{% endblock %}

{% block templateContentArea %}
    <div class="particles">
        <h1 class="servicecollection__header">Our services</h1>
        <div id="particles-js-services"></div>
    </div>

    <div class="tetrablocks">
        <h2 class="tetrablocks__header">All-in-one</h2>
        <section id="timeline">
            <div class="tl-item allinone__item_first">
                <div class="tl-year">
                    <a class="allinone__link" href="services/landing-page-development">Landing</a>
                </div>
                <div class="tl-content">
                    <p>Landing has significant advantages over free website builders: no monthly fee - only pay for
                        hosting, adaptive templates, full customization</p>
                </div>
            </div>

            <div class="tl-item allinone__item_second">
                <div class="tl-year">
                    <a class="allinone__link" href="services/business-website-b2c-development">Website</a>
                </div>
                <div class="tl-content">
                    <p>The B2C website contains detailed information about the business, services, and prices</p>
                </div>
            </div>

            <div class="tl-item allinone__item_third">
                <div class="tl-year">
                    <a class="allinone__link" class="" href="services/online-store-development-woocommerce">Store</a>
                </div>
                <div class="tl-content">
                    <p>An important feature of the online store is the catalog of goods that the visitor can select, add
                        to the cart and place an order</p>
                </div>
            </div>

            <div class="tl-item allinone__item_four">
                <div class="tl-year">
                    <a class="allinone__link" href="services/responsive-web-design-development-for-devices">Mobile</a>
                </div>
                <div class="tl-content">
                    <p>Responsive design is convenient for smartphone and tablet users, and it is a necessary feature
                        for the site's ranking in the Google search engine</p>
                </div>
            </div>
        </section>
        <div class="timeline__mobile">
            <div class="allinone__item_first allinone__item_mobile">
                <div class="allinone__mobile_head">
                    <a href="/services/landing-page-development">Landing Page</a>
                </div>
                <div class="allinone__mobile_desc">
                    <p>Landing has significant advantages over free website builders: no monthly fee - only pay for
                        hosting, adaptive templates, full customization</p>
                </div>
            </div>
            <div class="allinone__item_second allinone__item_mobile">
                <div class="allinone__mobile_head">
                    <a href="services/business-website-b2c-development">B2C Website</a>
                </div>
                <div class="allinone__mobile_desc">
                    <p>The B2C website contains detailed information about the business, services, and prices</p>
                </div>
            </div>
            <div class="allinone__item_third allinone__item_mobile">
                <div class="allinone__mobile_head">
                    <a href="services/online-store-development-woocommerce">E-commerce Store </a>
                </div>
                <div class="allinone__mobile_desc">
                    <p>An important feature of the online store is the catalog of goods that the visitor can select, add
                        to the cart and place an order</p>
                </div>
            </div>
            <div class="allinone__item_four allinone__item_mobile">
                <div class="allinone__mobile_head">
                    <a href="services/responsive-web-design-development-for-devices">Responsive Design</a>
                </div>
                <div class="allinone__mobile_desc">
                    <p>Responsive design is convenient for smartphone and tablet users, and it is a necessary feature
                        for the site's ranking in the Google search engine.</p>
                </div>
            </div>
        </div>
    </div>


    <div class="servicecollection_development">
        <h2 class="tetrablocks__header">Development</h2>
        <div class="servicecollection__grid uk-animation-toggle" tabindex="0">
            <a class="uk-card uk-card-body servicecollection__card_one servicecollection__card_position">
                <h3 class="uk-card-title service__block_wheat"><span class="services__icon"
                                                                     uk-icon="icon:  arrow-right; ratio: 1.5"></span>Landing
                    Page</h3>
            </a>
            <a class="uk-card uk-card-body servicecollection__card_one servicecollection__card_position">
                <h3 class="uk-card-title service__block_wheat"><span class="services__icon"
                                                                     uk-icon="icon: check; ratio: 1.5"></span>Business
                    Site | B2C site</h3>
            </a>
            <a class="uk-card uk-card-body servicecollection__card_one servicecollection__card_position">
                <h3 class="uk-card-title service__block_wheat"><span class="services__icon"
                                                                     uk-icon="icon: wordpress; ratio: 1.5"></span>WordPress
                    development</h3>
            </a>
            <a class="uk-card uk-card-body servicecollection__card_one servicecollection__card_position">
                <h3 class="uk-card-title service__block_wheat"><span class="services__icon"
                                                                     uk-icon="icon: cart; ratio: 1.5"></span>Woo
                    Commerce development</h3>
            </a>
            <a class="uk-card uk-card-body servicecollection__card_one servicecollection__card_position">
                <h3 class="uk-card-title service__block_wheat"><span class="services__icon"
                                                                     uk-icon="icon: cart; ratio: 1.5"></span>Symfony
                    Development</h3>
            </a>
            <a class="uk-card uk-card-body servicecollection__card_one servicecollection__card_position">
                <h3 class="uk-card-title service__block_wheat"><span class="services__icon"
                                                                     uk-icon="icon: cart; ratio: 1.5"></span>Tilda
                    Development</h3>
            </a>
            <a class="uk-card uk-card-body servicecollection__card_one servicecollection__card_position">
                <h3 class="uk-card-title service__block_wheat"><span class="services__icon"
                                                                     uk-icon="icon: cart; ratio: 1.5"></span>
                    Shopify Online Store</h3>
            </a>
            <a class="uk-card uk-card-body servicecollection__card_one servicecollection__card_position">
                <h3 class="uk-card-title service__block_wheat"><span class="services__icon"
                                                                     uk-icon="icon: phone; ratio: 1.5"></span>Mobile
                    sites</h3>
            </a>
        </div>
    </div>
    <a href="#support"></a>
    <div class="servicecollection_support">
        <h2 class="tetrablocks__header"><a class="support__anchor_link" name="support">Support</a>
        </h2>
        <div class="homepage__services servicecollection__offer homepage__services_second">
            <div class="servicecollection__grid uk-animation-toggle" tabindex="0">
                <a href="/services/online-store-website-maintenance-upgrade-service" class="uk-card uk-card-body servicecollection__card_two servicecollection__card_position">
                    <h3 class="uk-card-title service__block_wheat"><span class="services__icon"
                                                                         uk-icon="icon: nut; ratio: 1.5"></span>Maintenance & Upgrade
                    </h3>
                </a>
                <a class="uk-card uk-card-body servicecollection__card_two servicecollection__card_position">
                    <h3 class="uk-card-title service__block_wheat"><span class="services__icon"
                                                                         uk-icon="icon: pencil; ratio: 1.5"></span>Content
                        Managment</h3>
                </a>
                <a class="uk-card uk-card-body servicecollection__card_two servicecollection__card_position">
                    <h3 class="uk-card-title service__block_wheat"><span class="services__icon"
                                                                         uk-icon="icon: file-text; ratio: 1.5"></span>SEO
                        Optimization</h3>
                </a>
                <a class="uk-card uk-card-body servicecollection__card_two servicecollection__card_position">
                    <h3 class="uk-card-title service__block_wheat"><span class="services__icon"
                                                                         uk-icon="icon: pencil; ratio: 1.5"></span>QA
                    </h3>
                </a>
                <a class="uk-card uk-card-body servicecollection__card_two servicecollection__card_position">
                    <h3 class="uk-card-title service__block_wheat"><span class="services__icon"
                                                                         uk-icon="icon: server; ratio: 1.5"></span>Hosting
                        configuration</h3>
                </a>
                <a class="uk-card uk-card-body servicecollection__card_two servicecollection__card_position">
                    <h3 class="uk-card-title service__block_wheat"><span class="services__icon"
                                                                         uk-icon="icon: nut; ratio: 1.5"></span>Legacy
                        project support</h3>
                </a>
                <a class="uk-card uk-card-body servicecollection__card_two servicecollection__card_position">
                    <h3 class="uk-card-title service__block_wheat"><span class="services__icon"
                                                                         uk-icon="icon: database; ratio: 1.5"></span>Symfony
                        support</h3>
                </a>
                <a class="uk-card uk-card-body servicecollection__card_two servicecollection__card_position">
                    <h3 class="uk-card-title service__block_wheat"><span class="services__icon"
                                                                         uk-icon="icon: database; ratio: 1.5"></span>Site
                        audit compliance</h3>
                </a>
                <a class="uk-card uk-card-body servicecollection__card_two servicecollection__card_position">
                    <h3 class="uk-card-title service__block_wheat"><span class="services__icon"
                                                                         uk-icon="icon: database; ratio: 1.5"></span>Facebook
                        Pixel && Google Tag Manager</h3>
                </a>
            </div>
        </div>
    </div>

    {{ include('client-side/__contactFooter.html.twig') }}

{% endblock %}